# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: build and deploy docs

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  publish:
    name: "Build and publish docs"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0
          run_install: |
            - args: []
      - run: pnpm build
      - name: Setup git config
        run: |
          git config --global user.name "github-actions[bot]" &&
          git config --global user.email "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          echo "GIT_USER=${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - name: Deploy docs
        run: |
          pnpm --filter @tlgr/docs run deploy
